name: Build and Deploy React App

on:
  push:
    branches: [ main ]
    paths: 
      - 'data/**'
      - 'webapp/**'
      - '.github/workflows/deploy-webapp.yml'
  workflow_dispatch:
  repository_dispatch:
    types: [data-updated]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './webapp/package-lock.json'

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Generate webapp data index
      run: |
        chmod +x generate_webapp_data.py
        python3 generate_webapp_data.py

    - name: Install webapp dependencies
      run: |
        cd webapp
        npm install

    - name: Build React app
      run: |
        cd webapp
        npm run build
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './webapp/build'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
